import { randomUUID } from "node:crypto";
import { and, eq, sql } from "drizzle-orm";
import type { Database } from "@/db/client";
import { orderSources, orders } from "@/db/schema";
import { DomainError } from "./errors";
import { assertAdminActionContext, type AdminActionContext } from "./admin-action-context";
const defaults = [{ key: "WEBSITE", labelFi: "Verkkosivu", labelEn: "Website" }, { key: "SMS", labelFi: "SMS", labelEn: "SMS" }, { key: "WHATSAPP", labelFi: "WhatsApp", labelEn: "WhatsApp" }, { key: "FACEBOOK", labelFi: "Facebook-viesti", labelEn: "Facebook message" }, { key: "PHONE", labelFi: "Puhelin", labelEn: "Phone" }, { key: "OTHER", labelFi: "Muu", labelEn: "Other" }];
function actorName(context: AdminActionContext) { assertAdminActionContext(context); return context.actor.email ?? context.actor.id; }
export async function listAdminOrderSources(database: Database, context: AdminActionContext) { assertAdminActionContext(context); let rows = await database.select().from(orderSources).where(eq(orderSources.shopId, context.shop.id)); if (!rows.length) { const now = new Date().toISOString(); await database.insert(orderSources).values(defaults.map((item, index) => ({ id: randomUUID(), shopId: context.shop.id, ...item, active: true, sortOrder: index, createdAt: now, updatedAt: now }))); rows = await database.select().from(orderSources).where(eq(orderSources.shopId, context.shop.id)); } return rows.sort((a, b) => a.sortOrder - b.sortOrder); }
export async function createAdminOrderSource(database: Database, context: AdminActionContext, input: { key: string; labelFi: string; labelEn: string; active: boolean; sortOrder: number }) { const now = new Date().toISOString(); const [row] = await database.insert(orderSources).values({ id: randomUUID(), shopId: context.shop.id, ...input, createdAt: now, updatedAt: now }).returning(); if (!row) throw new DomainError("CREATE_FAILED", "Order source could not be created", 500); return { ...row, updatedBy: actorName(context) }; }
export async function updateAdminOrderSource(database: Database, context: AdminActionContext, id: string, values: Partial<{ key: string; labelFi: string; labelEn: string; active: boolean; sortOrder: number }>) { const [row] = await database.update(orderSources).set({ ...values, updatedAt: new Date().toISOString() }).where(and(eq(orderSources.id, id), eq(orderSources.shopId, context.shop.id))).returning(); if (!row) throw new DomainError("NOT_FOUND", "Order source not found", 404); return { ...row, updatedBy: actorName(context) }; }
export async function deleteAdminOrderSource(database: Database, context: AdminActionContext, id: string) { const current = await database.query.orderSources.findFirst({ where: and(eq(orderSources.id, id), eq(orderSources.shopId, context.shop.id)) }); if (!current) throw new DomainError("NOT_FOUND", "Order source not found", 404); if (["WEBSITE", "MANUAL", "HISTORICAL"].includes(current.key)) throw new DomainError("FORBIDDEN", "Cannot delete system core channel. Deactivate it instead.", 409); const [{ count }] = await database.select({ count: sql<number>`count(*)` }).from(orders).where(and(eq(orders.shopId, context.shop.id), eq(orders.orderSource, current.key))); if (Number(count) > 0) throw new DomainError("CONFLICT", `Cannot delete channel: used in ${count} historical orders. Deactivate it instead.`, 409); await database.delete(orderSources).where(and(eq(orderSources.id, id), eq(orderSources.shopId, context.shop.id))); return { deleted: true, id, updatedBy: actorName(context) }; }
