import { randomUUID } from "node:crypto";
import { and, eq, like, or, sql } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db/client";
import { fulfillmentLocations, orders } from "@/db/schema";
import { requirePermission } from "@/domain/access";
import { DomainError } from "@/domain/errors";
import { env } from "@/lib/env";
import { failure, success } from "../../response";
import { executeAdmin } from "../module";
const input = z.object({ type: z.enum(["PICKUP", "DELIVERY_ORIGIN"]), nameFi: z.string().trim().min(2).max(120), nameEn: z.string().trim().min(2).max(120), address: z.string().trim().min(2).max(240), instructionsFi: z.string().max(1000).default(""), instructionsEn: z.string().max(1000).default(""), active: z.boolean().default(true), isDefault: z.boolean().default(false) });
export async function GET(request: Request) { try { return success(await executeAdmin(request, { permission: "settings.fulfillment.read", parse: async () => undefined, run: async (_input, { database }) => database.select().from(fulfillmentLocations).where(eq(fulfillmentLocations.shopId, env().SHOP_ID)) })); } catch (error) { return failure(error); } }
export async function POST(request: Request) { try { const actor = await requirePermission(db(), request, "settings.fulfillment.manage"); const parsed = input.safeParse(await request.json()); if (!parsed.success) throw new DomainError("VALIDATION_ERROR", "Invalid fulfillment location", 422); const now = new Date().toISOString(); const id = randomUUID(); await db().transaction(async (tx) => { if (parsed.data.isDefault) await tx.update(fulfillmentLocations).set({ isDefault: false }).where(and(eq(fulfillmentLocations.shopId, env().SHOP_ID), eq(fulfillmentLocations.type, parsed.data.type))); await tx.insert(fulfillmentLocations).values({ id, shopId: env().SHOP_ID, ...parsed.data, createdAt: now, updatedAt: now }); }); const row = await db().query.fulfillmentLocations.findFirst({ where: eq(fulfillmentLocations.id, id) }); return success({ ...row, updatedBy: actor.email ?? actor.id }, 201); } catch (error) { return failure(error); } }
export async function PATCH(request: Request) { try { const actor = await requirePermission(db(), request, "settings.fulfillment.manage"); const body = await request.json() as { id?: string } & Partial<z.infer<typeof input>>; if (!body.id) throw new DomainError("VALIDATION_ERROR", "Location id is required", 422); const locationId = body.id; const parsed = input.partial().safeParse(body); if (!parsed.success) throw new DomainError("VALIDATION_ERROR", "Invalid fulfillment location", 422); const current = await db().query.fulfillmentLocations.findFirst({ where: and(eq(fulfillmentLocations.id, locationId), eq(fulfillmentLocations.shopId, env().SHOP_ID)) }); if (!current) throw new DomainError("NOT_FOUND", "Fulfillment location not found", 404); await db().transaction(async (tx) => { if (parsed.data.isDefault) await tx.update(fulfillmentLocations).set({ isDefault: false }).where(and(eq(fulfillmentLocations.shopId, env().SHOP_ID), eq(fulfillmentLocations.type, parsed.data.type ?? current.type))); await tx.update(fulfillmentLocations).set({ ...parsed.data, updatedAt: new Date().toISOString() }).where(eq(fulfillmentLocations.id, locationId)); }); const row = await db().query.fulfillmentLocations.findFirst({ where: eq(fulfillmentLocations.id, locationId) }); return success({ ...row, updatedBy: actor.email ?? actor.id }); } catch (error) { return failure(error); } }
export async function DELETE(request: Request) { try { const actor = await requirePermission(db(), request, "settings.fulfillment.manage"); const { searchParams } = new URL(request.url); const id = searchParams.get("id"); if (!id) throw new DomainError("VALIDATION_ERROR", "Location id is required", 422); const current = await db().query.fulfillmentLocations.findFirst({ where: and(eq(fulfillmentLocations.id, id), eq(fulfillmentLocations.shopId, env().SHOP_ID)) }); if (!current) throw new DomainError("NOT_FOUND", "Fulfillment location not found", 404); if (current.isDefault) throw new DomainError("FORBIDDEN", "Cannot delete system default location. Set another location as default first.", 409); const [{ count }] = await db().select({ count: sql<number>`count(*)` }).from(orders).where(and(eq(orders.shopId, env().SHOP_ID), or(eq(orders.pickupName, current.nameFi), eq(orders.pickupName, current.nameEn), like(orders.pickupLocationSnapshotJson, `%${id}%`)))); if (Number(count) > 0) throw new DomainError("CONFLICT", `Cannot delete location: linked to ${count} historical orders. Deactivate it instead.`, 409); await db().delete(fulfillmentLocations).where(and(eq(fulfillmentLocations.id, id), eq(fulfillmentLocations.shopId, env().SHOP_ID))); return success({ deleted: true, id, updatedBy: actor.email ?? actor.id }); } catch (error) { return failure(error); } }
