"use client";

import { useState, type FormEvent } from "react";
import { AdminNotice } from "../../../presentation";

type Product = { id: string; code: string; slug: string; nameFi: string; nameEn: string; descriptionFi: string; descriptionEn: string; availableFrom: string; availableThrough: string; active: boolean; showOnHomepage: boolean; showOnReserve: boolean };

export function ProductEditView({ initial, impact }: { initial: Product; impact: { activeOrders: number; availabilityRows: number } }) {
  const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const values = new FormData(event.currentTarget); const payload = { code: values.get("code"), slug: values.get("slug"), nameFi: values.get("nameFi"), nameEn: values.get("nameEn"), descriptionFi: values.get("descriptionFi"), descriptionEn: values.get("descriptionEn"), availableFrom: values.get("availableFrom"), availableThrough: values.get("availableThrough"), active: values.get("active") === "on", showOnHomepage: values.get("showOnHomepage") === "on", showOnReserve: values.get("showOnReserve") === "on" }; const response = await fetch(`/api/admin/products/${initial.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "update", product: payload }) }); const body = await response.json(); if (!response.ok) return setError(body.message ?? "Product could not be updated."); setMessage("Product updated."); }
  return <section className="product-edit-workspace">{message && <AdminNotice tone="success" live>{message}</AdminNotice>}{error && <AdminNotice tone="error" live>{error}</AdminNotice>}<div className="product-impact-warning card"><strong>Change impact preview</strong><span>{impact.activeOrders} active order(s) and {impact.availabilityRows} availability row(s) are linked to this product. Duration changes are rejected if they would exclude confirmed work or reserved capacity.</span></div><form className="card grid gap-4" onSubmit={(event) => void save(event)}><div className="grid gap-3 md:grid-cols-2"><label className="field"><span>Product code *</span><input name="code" defaultValue={initial.code} required /></label><label className="field"><span>Slug *</span><input name="slug" defaultValue={initial.slug} required /></label><label className="field"><span>Finnish name *</span><input name="nameFi" defaultValue={initial.nameFi} required /></label><label className="field"><span>English name *</span><input name="nameEn" defaultValue={initial.nameEn} required /></label><label className="field"><span>Available from *</span><input name="availableFrom" type="date" defaultValue={initial.availableFrom} required /></label><label className="field"><span>Available through *</span><input name="availableThrough" type="date" defaultValue={initial.availableThrough} required /></label></div><div className="grid gap-3 md:grid-cols-2"><label className="field"><span>Finnish description</span><textarea name="descriptionFi" defaultValue={initial.descriptionFi} rows={4}/></label><label className="field"><span>English description</span><textarea name="descriptionEn" defaultValue={initial.descriptionEn} rows={4}/></label></div><div className="flex flex-wrap gap-5"><label><input name="active" type="checkbox" defaultChecked={initial.active}/> Active</label><label><input name="showOnHomepage" type="checkbox" defaultChecked={initial.showOnHomepage}/> Homepage visibility</label><label><input name="showOnReserve" type="checkbox" defaultChecked={initial.showOnReserve}/> Reserve visibility</label></div><div className="profile-actions"><a className="btn btn-secondary" href={`/admin/products/${initial.id}`}>Cancel</a><button className="btn" type="submit">Save product</button></div></form></section>;
}
