"use client";

import { useState, type FormEvent } from "react";
import { AdminNotice } from "../../presentation";

export function ProductCreateView() {
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const values = new FormData(event.currentTarget); const response = await fetch("/api/admin/products", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ code: values.get("code"), slug: values.get("slug"), nameFi: values.get("nameFi"), nameEn: values.get("nameEn"), descriptionFi: values.get("descriptionFi"), descriptionEn: values.get("descriptionEn"), availableFrom: values.get("availableFrom"), availableThrough: values.get("availableThrough"), active: true, showOnHomepage: values.get("showOnHomepage") === "on", showOnReserve: values.get("showOnReserve") === "on", packages: [{ labelFi: "10 litran sanko", labelEn: "10 litre bucket", volumeMl: 10000, priceCents: Math.round(Number(values.get("price")) * 100), active: true, isDefault: true }] }) }); const body = await response.json(); setSaving(false); if (!response.ok) return setError(body.message ?? "Product could not be created."); window.location.assign(`/admin/products/${body.data.product.id}`); }
  return <form className="card grid gap-4" onSubmit={(event) => void submit(event)}>{error && <AdminNotice tone="error" live>{error}</AdminNotice>}<div className="grid gap-3 md:grid-cols-2"><label className="field"><span>Product code *</span><input name="code" required placeholder="MUSTIKKA" /></label><label className="field"><span>Slug *</span><input name="slug" required placeholder="mustikka" /></label><label className="field"><span>Finnish name *</span><input name="nameFi" required /></label><label className="field"><span>English name *</span><input name="nameEn" required /></label><label className="field"><span>Available from *</span><input name="availableFrom" type="date" required /></label><label className="field"><span>Available through *</span><input name="availableThrough" type="date" required /></label><label className="field"><span>Initial 10L package price (€) *</span><input name="price" type="number" min="0" step="0.01" required /></label></div><div className="grid gap-3 md:grid-cols-2"><label className="field"><span>Finnish description</span><textarea name="descriptionFi" rows={4}/></label><label className="field"><span>English description</span><textarea name="descriptionEn" rows={4}/></label></div><div className="flex flex-wrap gap-5"><label><input name="showOnHomepage" type="checkbox" defaultChecked/> Homepage visibility</label><label><input name="showOnReserve" type="checkbox" defaultChecked/> Reserve visibility</label></div><div className="profile-actions"><a className="btn btn-secondary" href="/admin/products">Cancel</a><button className="btn" type="submit" disabled={saving}>{saving ? "Creating…" : "Create product"}</button></div></form>;
}
