import type { Meta, StoryObj } from "@storybook/react";

const users = [
  { name: "Tuan Huynh", email: "admin@metsanilo.local", role: "ADMIN", access: "Full access", state: "Active" },
  { name: "Aino Korhonen", email: "aino@metsanilo.local", role: "MANAGER", access: "Operations lead", state: "Active" },
  { name: "Mika Salonen", email: "mika@metsanilo.local", role: "STAFF", access: "Fulfilment", state: "Password reset" },
];

function UsersPreview({ permissions = true }: { permissions?: boolean }) {
  return <main className="admin-users-workspace shell pb-10 flex flex-col gap-4"><div className="grid gap-3 grid-cols-2 md:grid-cols-4"><div className="card p-3.5"><span className="eyebrow">Total team</span><p className="text-2xl font-black">8</p><small>Active roster</small></div><div className="card p-3.5"><span className="eyebrow">Admin &amp; manager</span><p className="text-2xl font-black">3</p><small>Executive access</small></div><div className="card p-3.5"><span className="eyebrow">Staff &amp; creators</span><p className="text-2xl font-black">5</p><small>Operations &amp; content</small></div><div className="card p-3.5"><span className="eyebrow">Custom overrides</span><p className="text-2xl font-black">2</p><small>Granted / revoked</small></div></div><div className="flex flex-wrap items-center justify-between gap-3 bg-surface-muted rounded-xl border border-line"><div className="flex items-center gap-2"><button className="btn" type="button">Split view</button><button className="btn btn-secondary" type="button">Table matrix</button></div><button className="btn" type="button">Onboard user</button></div><div className="grid gap-4 lg:grid-cols-12"><section className="card p-4 lg:col-span-5"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-line pb-3"><div><p className="eyebrow">Team directory</p><h2>Staff access</h2></div><input aria-label="Search users" placeholder="Search name or email" /></div><div className="grid gap-2 mt-3">{users.map((user) => <button className={`admin-user-row ${permissions && user.name === "Aino Korhonen" ? "selected" : ""}`} key={user.email} type="button"><span className="admin-user-row-copy"><strong>{user.name}</strong><small>{user.email}</small></span><span className="status-pill status-active">{user.role}</span><small>{user.state}</small></button>)}</div></section><section className="card p-5 lg:col-span-7"><p className="eyebrow">Permission matrix</p><h2>{permissions ? "Aino Korhonen" : "Select a team member"}</h2>{permissions ? <><p className="text-sm muted">Manager preset with operational access. Review high-risk permissions before saving overrides.</p><div className="grid gap-3 mt-5">{["Orders & fulfilment", "Harvest capacity", "Customer context", "Product catalog"].map((group) => <div className="card p-3" key={group}><div className="flex items-center justify-between"><strong>{group}</strong><span className="pill">Preset</span></div><small className="muted">Read, update, and transition permissions</small></div>)}</div><div className="profile-actions mt-5"><button className="btn btn-secondary" type="button">View audit</button><button className="btn" type="button">Save permissions</button></div></> : <p className="muted mt-3">Choose a team member to inspect sessions, audit history, role defaults, and custom overrides.</p>}</section></div></main>;
}

const meta = { title: "Admin / Users", component: UsersPreview, parameters: { layout: "fullscreen" }, argTypes: { permissions: { control: "boolean" } } } satisfies Meta<typeof UsersPreview>;
export default meta;
type Story = StoryObj<typeof meta>;
export const PermissionMatrix: Story = { args: { permissions: true } };
export const NoSelection: Story = { args: { permissions: false } };
