import { randomUUID } from "node:crypto";
import { z } from "zod";
import { and, eq } from "drizzle-orm";
import { db } from "@/db/client";
import { auditEntries, customers } from "@/db/schema";
import { requirePermission } from "@/domain/access";
import { normalizeEmail, normalizeMobile } from "@/domain/order-input";
import { getCustomerProfile } from "@/domain/customers";
import { env } from "@/lib/env";
import { DomainError } from "@/domain/errors";
import { failure, success } from "../../../response";
export const runtime = "nodejs";
const update = z.object({ name: z.string().min(2).max(120), mobile: z.string().min(3).max(40), email: z.preprocess((value) => typeof value === "string" ? value.trim().toLowerCase() : value, z.string().email().optional().or(z.literal(""))), marketingConsent: z.boolean().optional() });
export async function GET(request: Request, context: { params: Promise<{ id: string }> }) { try { await requirePermission(db(), request, "customers.read"); const { id } = await context.params; const profile = await getCustomerProfile(db(), id); if (!profile) throw new DomainError("NOT_FOUND", "Customer not found", 404); return success(profile); } catch (error) { return failure(error); } }
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { try { const actor = await requirePermission(db(), request, "customers.write"); const { id } = await context.params; const parsed = update.safeParse(await request.json()); if (!parsed.success) throw new DomainError("VALIDATION_ERROR", "Invalid customer details", 422); let mobile: string; try { mobile = normalizeMobile(parsed.data.mobile); } catch { throw new DomainError("VALIDATION_ERROR", "Invalid phone", 422, { mobile: "INVALID_PHONE" }); } const now = new Date().toISOString(); const consentChanged = parsed.data.marketingConsent !== undefined; const consentStatus = consentChanged ? (parsed.data.marketingConsent ? "CONSENTED" as const : "REVOKED" as const) : undefined; const changed = await db().update(customers).set({ name: parsed.data.name.trim(), mobile, email: normalizeEmail(parsed.data.email), ...(consentChanged ? { marketingConsent: parsed.data.marketingConsent, marketingConsentStatus: consentStatus, marketingConsentAt: now, marketingConsentSource: "ADMIN" as const, marketingConsentUpdatedBy: actor.email ?? actor.username ?? actor.id } : {}), updatedAt: now }).where(and(eq(customers.id, id), eq(customers.shopId, env().SHOP_ID))).run(); if (changed.rowsAffected !== 1) throw new DomainError("NOT_FOUND", "Customer not found", 404); await db().insert(auditEntries).values({ id: randomUUID(), shopId: env().SHOP_ID, actor: actor.email ?? actor.username ?? actor.id, action: consentChanged ? "customer.marketing_consent_updated" : "customer.updated", entityType: "customer", entityId: id, detailsJson: JSON.stringify({ fields: consentChanged ? ["marketingConsent", "marketingConsentStatus"] : ["name", "mobile", "email"], marketingConsent: parsed.data.marketingConsent, marketingConsentStatus: consentStatus }), createdAt: now }); return success((await db().query.customers.findFirst({ where: eq(customers.id, id) }))!); } catch (error) { return failure(error); } }
export async function POST(request: Request, context: { params: Promise<{ id: string }> }) { try { const actor = await requirePermission(db(), request, "customers.write"); const { id } = await context.params; const now = new Date().toISOString(); const changed = await db().update(customers).set({ name: "Anonymized customer", mobile: `ANONYMIZED-${id.slice(0, 8)}`, email: null, marketingConsent: false, marketingConsentStatus: "REVOKED", marketingConsentAt: now, marketingConsentSource: "ADMIN", marketingConsentUpdatedBy: actor.email ?? actor.username ?? actor.id, notes: "Personal data anonymized by authorized user.", updatedAt: now }).where(and(eq(customers.id, id), eq(customers.shopId, env().SHOP_ID))).run(); if (changed.rowsAffected !== 1) throw new DomainError("NOT_FOUND", "Customer not found", 404); await db().insert(auditEntries).values({ id: randomUUID(), shopId: env().SHOP_ID, actor: actor.email ?? actor.username ?? actor.id, action: "customer.anonymized", entityType: "customer", entityId: id, detailsJson: JSON.stringify({ reason: "customer request or retention policy", marketingConsent: false, marketingConsentStatus: "REVOKED" }), createdAt: now }); return success({ anonymized: true }); } catch (error) { return failure(error); } }
