"use client";

import { useEffect, useState } from "react";
import { AdminEmptyState, AdminLoadingState, AdminNotice, AdminPageHeader } from "./presentation";

type Customer = { id: string; name: string; mobile: string; email: string | null; matchStatus: string; notes: string | null; updatedAt: string };
type Profile = { customer: Customer; orders: Array<{ id: string; publicReference: string; status: string; fulfillmentDate: string; fulfillmentMethod: string; volumeMl: number; finalTotalCents: number | null; createdAt: string }>; audit: Array<{ id: string; action: string; actor: string; createdAt: string }> };

function formatDate(value: string) { return new Intl.DateTimeFormat("fi-FI", { dateStyle: "medium" }).format(new Date(value)); }
function formatMoney(cents: number | null) { return cents === null ? "—" : new Intl.NumberFormat("fi-FI", { style: "currency", currency: "EUR" }).format(cents / 100); }

export function CustomersModule() {
  const [rows, setRows] = useState<Customer[]>([]); const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [profile, setProfile] = useState<Profile | null>(null); const [loading, setLoading] = useState(false);
  async function load(value = query) { setLoading(true); const response = await fetch(`/api/admin/customers?q=${encodeURIComponent(value)}`); const body = await response.json(); setLoading(false); if (response.ok) setRows(body.data); else setMessage(body.message ?? "Customers unavailable"); }
  useEffect(() => { void load(""); }, []);
  async function openProfile(row: Customer) { const response = await fetch(`/api/admin/customers/${row.id}`); const body = await response.json(); if (!response.ok) return setMessage(body.message ?? "Customer details unavailable"); setProfile(body.data); }
  async function edit(row: Customer) { const name = window.prompt("Customer name", row.name)?.trim(); const mobile = window.prompt("Mobile number", row.mobile)?.trim(); if (!name || !mobile) return; const email = window.prompt("Email (optional)", row.email ?? "")?.trim() ?? ""; const response = await fetch(`/api/admin/customers/${row.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, mobile, email }) }); const body = await response.json(); if (!response.ok) return setMessage(body.message ?? "Request failed"); setRows((items) => items.map((item) => item.id === row.id ? body.data : item)); setMessage("Customer updated."); if (profile?.customer.id === row.id) void openProfile(body.data); }
  async function anonymize(row: Customer) { if (!window.confirm(`Anonymize ${row.name}? This removes personal contact details.`)) return; const response = await fetch(`/api/admin/customers/${row.id}`, { method: "POST" }); const body = await response.json(); if (!response.ok) return setMessage(body.message ?? "Request failed"); setRows((items) => items.map((item) => item.id === row.id ? { ...item, name: "Anonymized customer", mobile: "ANONYMIZED", email: null } : item)); setProfile(null); setMessage("Customer anonymized."); }
  return <section className="shell pb-10"><AdminPageHeader eyebrow="CUSTOMER CONTEXT" title="Customers" description="Find a customer, review their order history, or update their contact details." actions={<form className="flex w-full gap-2 sm:w-auto" onSubmit={(event) => { event.preventDefault(); void load(); }}><input className="min-w-0 flex-1 rounded-lg border p-3 sm:w-72" aria-label="Search customers" placeholder="Name, mobile or email" value={query} onChange={(event) => setQuery(event.target.value)} /><button className="btn" type="submit">Search</button></form>} />{message && <AdminNotice tone="success" live>{message}</AdminNotice>}<div className="mt-3 grid gap-3">{rows.map((row) => <article className="card flex flex-wrap items-center justify-between gap-3" key={row.id}><div className="min-w-0"><h3 className="font-bold">{row.name} {row.matchStatus === "CONFLICT_REVIEW" && <span className="pill">Review</span>}</h3><p className="break-words">{row.mobile}{row.email ? ` · ${row.email}` : ""}</p>{row.notes && <p className="text-sm text-slate-600">{row.notes}</p>}<p className="text-xs text-slate-500">Updated {formatDate(row.updatedAt)}</p></div><div className="flex flex-wrap gap-2"><a className="btn" href={`/admin/customers/${row.id}`}>View profile</a><button className="btn btn-secondary" onClick={() => void edit(row)}>Edit</button><button className="btn btn-secondary" onClick={() => void anonymize(row)}>Anonymize</button></div></article>)}{loading && <AdminLoadingState label="Loading customers…" />}{!loading && rows.length === 0 && <AdminEmptyState title="No customers found" description="Try a different name, mobile number, or email." />}</div></section>;
}
