"use client";

import { useMemo, useState } from "react";
import type { packages, products } from "@/db/schema";
import { AdminEmptyState, AdminNotice, AdminPageHeader, AdminStatusBadge } from "./presentation";

type ProductRow = { product: typeof products.$inferSelect; packages: Array<typeof packages.$inferSelect>; media?: Array<{ id: string; attachmentId?: string; url: string; altFi: string; altEn: string; isPrimary: boolean }> };

export function ProductModule({ initialProducts, canManageProducts }: { initialProducts: ProductRow[]; canManageProducts: boolean }) {
  const [rows, setRows] = useState(initialProducts); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [message, setMessage] = useState("");
  const visibleRows = useMemo(() => rows.filter((row) => { const text = `${row.product.nameFi} ${row.product.nameEn} ${row.product.code}`.toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (status === "all" || status === "active" && row.product.active || status === "archived" && !row.product.active); }), [rows, query, status]);
  async function toggle(row: ProductRow) { const response = await fetch(`/api/admin/products/${row.product.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "active", active: !row.product.active }) }); const body = await response.json(); if (!response.ok) return setMessage(body.message ?? "Could not change product status."); setRows((current) => current.map((item) => item.product.id === row.product.id ? body.data : item)); setMessage(row.product.active ? "Product archived." : "Product activated."); }
  function preview(row: ProductRow) { const popup = window.open("", "_blank", "noopener,noreferrer,width=560,height=720"); if (!popup) return setMessage("Allow pop-ups to preview the product."); const packagesList = row.packages.filter((item) => item.active).sort((a, b) => a.sortOrder - b.sortOrder).slice(0, 3).map((item) => `<li><b>${item.labelFi}</b><span>${(item.volumeMl / 1000).toFixed(1)} l · ${(item.priceCents / 100).toFixed(2)} €</span></li>`).join(""); popup.document.write(`<!doctype html><title>METSÄNILO preview</title><style>body{font:16px system-ui;margin:32px;background:#f6f3ec;color:#10241d}main{background:#fff;border-radius:20px;padding:24px;max-width:460px;margin:auto}h1{font:700 32px Georgia}li{display:flex;justify-content:space-between;padding:14px;border:1px solid #dce4df;border-radius:12px;margin:10px 0}span{color:#35634f}</style><main><small>PRODUCT PREVIEW · ${row.product.availableFrom} – ${row.product.availableThrough}</small><h1>${row.product.nameFi}</h1><p>${row.product.descriptionFi}</p><ul>${packagesList}</ul></main>`); popup.document.close(); }
  return <section className="shell pb-10"><AdminPageHeader eyebrow="CATALOG" title="Product catalog" description="Triage products, review publishing state, and open a dedicated detail or edit workspace." actions={canManageProducts ? <a className="btn" href="/admin/products/new">＋ New product</a> : undefined} />{message && <AdminNotice tone="success" live>{message}</AdminNotice>}<div className="admin-catalog-toolbar card mt-3"><div><p className="eyebrow">PRODUCT LISTING</p><h2>{visibleRows.length} products</h2><p className="muted">Creation, editing, packages and media are handled on dedicated routes.</p></div><div className="admin-catalog-actions"><input aria-label="Search products" placeholder="Search by name or code" value={query} onChange={(event) => setQuery(event.target.value)} /><select aria-label="Filter product status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="archived">Archived</option></select></div></div><div className="admin-product-list mt-3">{visibleRows.map((row) => <article className="card admin-product-list-row" key={row.product.id}><div className="admin-product-list-main"><div><div className="flex flex-wrap items-center gap-2"><h2>{row.product.nameFi}</h2><AdminStatusBadge status={row.product.active ? "CONFIRMED" : "CANCELLED"} label={row.product.active ? "Active" : "Archived"} /></div><p className="muted">{row.product.nameEn} · {row.product.code} · {row.product.availableFrom} – {row.product.availableThrough}</p><div className="admin-visibility-badges"><span className={row.product.showOnHomepage ? "is-on" : ""}>Homepage {row.product.showOnHomepage ? "on" : "off"}</span><span className={row.product.showOnReserve ? "is-on" : ""}>Reserve {row.product.showOnReserve ? "on" : "off"}</span><span>{row.packages.filter((item) => item.active).length} active packages</span><span>Default: {row.packages.find((item) => item.isDefault)?.labelFi ?? "Needs selection"}</span></div></div><div className="admin-product-actions"><a className="btn" href={`/admin/products/${row.product.id}`}>View detail</a>{canManageProducts && <a className="btn btn-secondary" href={`/admin/products/${row.product.id}/edit`}>Edit</a>}<button className="btn btn-secondary" type="button" onClick={() => preview(row)}>Preview</button>{canManageProducts && <button className="btn btn-secondary" type="button" onClick={() => void toggle(row)}>{row.product.active ? "Archive" : "Activate"}</button>}</div></div></article>)}{visibleRows.length === 0 && <AdminEmptyState title="No products found" description="Adjust the search or status filter." />}</div></section>;
}
