"use client";

import { useEffect, useState, type FormEvent } from "react";
import { AdminNotice, AdminPageHeader } from "./presentation";

type Method = { method: string; enabled: boolean };
type Contact = { phone: string; email: string; hours: string };

export function OperationsSettings() {
  const [methods, setMethods] = useState<Method[]>([]); const [contact, setContact] = useState<Contact>({ phone: "", email: "", hours: "" }); const [message, setMessage] = useState(""); const [tone, setTone] = useState<"success" | "error">("success");
  const feedback = (text: string, nextTone: "success" | "error") => { setMessage(text); setTone(nextTone); };
  async function load() { const response = await fetch("/api/admin/payment-methods"); const body = await response.json(); if (response.ok) setMethods(body.data); else feedback(body.code ?? "Operational settings unavailable", "error"); }
  async function loadContact() { const response = await fetch("/api/admin/contact"); const body = await response.json(); if (response.ok) setContact(body.data); else feedback(body.code ?? "Contact settings unavailable", "error"); }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); void loadContact(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function toggle(method: Method) { const response = await fetch("/api/admin/payment-methods", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ method: method.method, enabled: !method.enabled }) }); const body = await response.json(); if (!response.ok) return feedback(body.code ?? body.message ?? "Request failed", "error"); setMethods((rows) => rows.map((row) => row.method === method.method ? body.data : row)); feedback("Payment method updated.", "success"); }
  async function saveContact(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const response = await fetch("/api/admin/contact", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ phone: values.get("phone"), email: values.get("email"), hours: values.get("hours") }) }); const body = await response.json(); if (!response.ok) return feedback(body.message ?? body.code ?? "Contact settings update failed", "error"); setContact(body.data); feedback("Contact settings updated.", "success"); }
  return <section className="shell pb-10"><AdminPageHeader eyebrow="ADMINISTRATION" title="Operational settings" description="Enable payment methods and maintain customer-facing contact details." />{message && <AdminNotice tone={tone} live>{message}</AdminNotice>}<div className="card mt-3 grid gap-2 md:grid-cols-3">{methods.map((method) => <label className="field checkbox-field" key={method.method}><span>{method.method.replace("_", " ")}</span><input type="checkbox" checked={method.enabled} onChange={() => void toggle(method)} /></label>)}</div><form className="card mt-3 grid gap-3 md:grid-cols-3" onSubmit={saveContact}><h3 className="font-bold md:col-span-3">Customer contact</h3><label className="field"><span>Phone</span><input name="phone" type="tel" value={contact.phone} onChange={(event) => setContact({ ...contact, phone: event.target.value })} placeholder="+358 44 951 2904" /></label><label className="field"><span>Email</span><input name="email" type="email" value={contact.email} onChange={(event) => setContact({ ...contact, email: event.target.value })} placeholder="contact@example.fi" /></label><label className="field"><span>Contact hours</span><input name="hours" value={contact.hours} onChange={(event) => setContact({ ...contact, hours: event.target.value })} placeholder="08:00–20:00 Mon–Fri" /></label><button className="btn md:col-span-3" type="submit">Save contact details</button></form></section>;
}
