"use client";

import { useEffect, useState, type FormEvent } from "react";
import { AdminNotice, AdminPageHeader } from "./presentation";

type Method = { method: string; enabled: boolean };
type Contact = { phone: string; email: string; hours: string };
type Source = { id: string; key: string; labelFi: string; labelEn: string; active: boolean; sortOrder: number };
type Location = { id: string; type: "PICKUP" | "DELIVERY_ORIGIN"; nameFi: string; nameEn: string; address: string; instructionsFi: string; instructionsEn: string; active: boolean; isDefault: boolean };

export function OperationsSettings({ canManageSettings }: { canManageSettings: boolean }) {
  const [methods, setMethods] = useState<Method[]>([]); const [contact, setContact] = useState<Contact>({ phone: "", email: "", hours: "" }); const [sources, setSources] = useState<Source[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [reviewsVisible, setReviewsVisible] = useState(true); const [message, setMessage] = useState(""); const [tone, setTone] = useState<"success" | "error">("success");
  const feedback = (text: string, nextTone: "success" | "error") => { setMessage(text); setTone(nextTone); };
  async function request(url: string, options?: RequestInit) { const response = await fetch(url, options); const body = await response.json(); if (!response.ok) throw new Error(body.message ?? body.code ?? "Request failed"); return body.data; }
  async function loadAll() { try { const [methodsData, contactData, visibility, sourceData, locationData] = await Promise.all([request("/api/admin/payment-methods"), request("/api/admin/contact"), request("/api/admin/reviews/visibility"), request("/api/admin/order-sources"), request("/api/admin/fulfillment-locations")]); setMethods(methodsData); setContact(contactData); setReviewsVisible(visibility.visible); setSources(sourceData); setLocations(locationData); } catch (error) { feedback(error instanceof Error ? error.message : "Settings unavailable", "error"); } }
  useEffect(() => { void loadAll(); }, []);
  async function toggle(method: Method) { try { const data = await request("/api/admin/payment-methods", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ method: method.method, enabled: !method.enabled }) }); setMethods((rows) => rows.map((row) => row.method === method.method ? data : row)); feedback("Payment method updated.", "success"); } catch (error) { feedback(error instanceof Error ? error.message : "Update failed", "error"); } }
  async function saveContact(event: FormEvent<HTMLFormElement>) { event.preventDefault(); try { const values = new FormData(event.currentTarget); setContact(await request("/api/admin/contact", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ phone: values.get("phone"), email: values.get("email"), hours: values.get("hours") }) })); feedback("Contact settings updated.", "success"); } catch (error) { feedback(error instanceof Error ? error.message : "Update failed", "error"); } }
  async function toggleReviewsVisibility() { if (!window.confirm(`${reviewsVisible ? "Hide" : "Show"} Reviews page, homepage reviews and public review form?`)) return; try { const data = await request("/api/admin/reviews/visibility", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ visible: !reviewsVisible }) }); setReviewsVisible(data.visible); feedback("Review visibility updated.", "success"); } catch (error) { feedback(error instanceof Error ? error.message : "Update failed", "error"); } }
  async function saveSource(event: FormEvent<HTMLFormElement>, source: Source) { event.preventDefault(); try { const values = new FormData(event.currentTarget); const data = await request("/api/admin/order-sources", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: source.id, key: values.get("key"), labelFi: values.get("labelFi"), labelEn: values.get("labelEn"), sortOrder: Number(values.get("sortOrder")), active: values.get("active") === "on" }) }); setSources((rows) => rows.map((row) => row.id === source.id ? data : row)); feedback("Order source saved.", "success"); } catch (error) { feedback(error instanceof Error ? error.message : "Source update failed", "error"); } }
  async function saveLocation(event: FormEvent<HTMLFormElement>, location: Location) { event.preventDefault(); try { const values = new FormData(event.currentTarget); const data = await request("/api/admin/fulfillment-locations", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: location.id, type: values.get("type"), nameFi: values.get("nameFi"), nameEn: values.get("nameEn"), address: values.get("address"), instructionsFi: values.get("instructionsFi"), instructionsEn: values.get("instructionsEn"), active: values.get("active") === "on", isDefault: values.get("isDefault") === "on" }) }); setLocations((rows) => rows.map((row) => row.id === location.id ? data : row).map((row) => row.type === data.type && row.id !== data.id && data.isDefault ? { ...row, isDefault: false } : row)); feedback("Fulfillment location saved.", "success"); } catch (error) { feedback(error instanceof Error ? error.message : "Location update failed", "error"); } }
  async function addSource(event: FormEvent<HTMLFormElement>) { event.preventDefault(); try { const values = new FormData(event.currentTarget); const data = await request("/api/admin/order-sources", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ key: values.get("key"), labelFi: values.get("labelFi"), labelEn: values.get("labelEn"), sortOrder: Number(values.get("sortOrder") || sources.length) }) }); setSources((rows) => [...rows, data]); event.currentTarget.reset(); feedback("Order source added.", "success"); } catch (error) { feedback(error instanceof Error ? error.message : "Source could not be added", "error"); } }
  async function addLocation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); try { const values = new FormData(event.currentTarget); const data = await request("/api/admin/fulfillment-locations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type: values.get("type"), nameFi: values.get("nameFi"), nameEn: values.get("nameEn"), address: values.get("address"), instructionsFi: values.get("instructionsFi") || "", instructionsEn: values.get("instructionsEn") || "", isDefault: values.get("isDefault") === "on" }) }); setLocations((rows) => [...rows.filter((row) => !(row.type === data.type && data.isDefault)), data]); event.currentTarget.reset(); feedback("Fulfillment location added.", "success"); } catch (error) { feedback(error instanceof Error ? error.message : "Location could not be added", "error"); } }
  return <section className="shell pb-10"><AdminPageHeader eyebrow="ADMINISTRATION" title="Operational settings" description="Configure customer-facing contact, order sources, payment methods and fulfillment locations." />{message && <AdminNotice tone={tone} live>{message}</AdminNotice>}{!canManageSettings && <AdminNotice tone="success" live>Read-only access. An administrator or manager must change operational settings.</AdminNotice>}<div className="card mt-3 grid gap-2 md:grid-cols-3">{methods.map((method) => <label className="field checkbox-field" key={method.method}><span>{method.method.replace("_", " ")}</span><input type="checkbox" checked={method.enabled} disabled={!canManageSettings} onChange={() => void toggle(method)} /></label>)}</div>
    <div className="card mt-3 grid gap-3"><div><h3 className="font-bold">Order sources</h3><p className="text-sm text-slate-600">Edit labels and ordering; archive sources instead of deleting used history.</p></div>{sources.map((source) => <form className="grid gap-2 rounded-lg border p-3 md:grid-cols-5" key={source.id} onSubmit={(event) => void saveSource(event, source)}><input name="key" defaultValue={source.key} disabled={!canManageSettings} required /><input name="labelFi" defaultValue={source.labelFi} disabled={!canManageSettings} required /><input name="labelEn" defaultValue={source.labelEn} disabled={!canManageSettings} required /><input name="sortOrder" type="number" min="0" defaultValue={source.sortOrder} disabled={!canManageSettings} /><label className="flex items-center gap-2"><input name="active" type="checkbox" defaultChecked={source.active} disabled={!canManageSettings} /> Active</label>{canManageSettings && <button className="btn md:col-span-5" type="submit">Save source</button>}</form>)}{canManageSettings && <form className="grid gap-2 md:grid-cols-5" onSubmit={(event) => void addSource(event)}><input name="key" placeholder="KEY" required /><input name="labelFi" placeholder="Finnish label" required /><input name="labelEn" placeholder="English label" required /><input name="sortOrder" type="number" min="0" placeholder="Order" /><button className="btn" type="submit">Add source</button></form>}</div>
    <div className="card mt-3 grid gap-3"><div><h3 className="font-bold">Fulfillment locations</h3><p className="text-sm text-slate-600">Pickup and delivery origin are stored separately and snapshotted on each order.</p></div>{locations.map((location) => <form className="grid gap-2 rounded-lg border p-3 md:grid-cols-3" key={location.id} onSubmit={(event) => void saveLocation(event, location)}><select name="type" defaultValue={location.type} disabled={!canManageSettings}><option value="PICKUP">Pickup</option><option value="DELIVERY_ORIGIN">Delivery origin</option></select><input name="nameFi" defaultValue={location.nameFi} disabled={!canManageSettings} required /><input name="nameEn" defaultValue={location.nameEn} disabled={!canManageSettings} required /><input name="address" defaultValue={location.address} disabled={!canManageSettings} required /><input name="instructionsFi" defaultValue={location.instructionsFi} disabled={!canManageSettings} placeholder="Finnish instructions" /><input name="instructionsEn" defaultValue={location.instructionsEn} disabled={!canManageSettings} placeholder="English instructions" /><label className="flex items-center gap-2"><input name="active" type="checkbox" defaultChecked={location.active} disabled={!canManageSettings} /> Active</label><label className="flex items-center gap-2"><input name="isDefault" type="checkbox" defaultChecked={location.isDefault} disabled={!canManageSettings} /> Default for this type</label>{canManageSettings && <button className="btn md:col-span-3" type="submit">Save location</button>}</form>)}{canManageSettings && <form className="grid gap-2 md:grid-cols-4" onSubmit={(event) => void addLocation(event)}><select name="type"><option value="PICKUP">Pickup</option><option value="DELIVERY_ORIGIN">Delivery origin</option></select><input name="nameFi" placeholder="Finnish name" required /><input name="nameEn" placeholder="English name" required /><input name="address" placeholder="Address" required /><input name="instructionsFi" placeholder="Finnish instructions" /><input name="instructionsEn" placeholder="English instructions" /><label className="flex items-center gap-2"><input name="isDefault" type="checkbox" /> Default</label><button className="btn" type="submit">Add location</button></form>}</div>
    <div className="card mt-3 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Reviews page visibility</h3><p className="text-sm text-slate-600">Controls the Reviews page, homepage review section and public review form together.</p></div><button className="btn btn-secondary" disabled={!canManageSettings} type="button" onClick={() => void toggleReviewsVisibility()}>{reviewsVisible ? "Visible on customer site" : "Hidden on customer site"}</button></div>
    <form className="card mt-3 grid gap-3 md:grid-cols-3" onSubmit={(event) => void saveContact(event)}><h3 className="font-bold md:col-span-3">Customer contact</h3><label className="field"><span>Phone</span><input name="phone" type="tel" disabled={!canManageSettings} value={contact.phone} onChange={(event) => setContact({ ...contact, phone: event.target.value })} /></label><label className="field"><span>Email</span><input name="email" type="email" disabled={!canManageSettings} value={contact.email} onChange={(event) => setContact({ ...contact, email: event.target.value })} /></label><label className="field"><span>Contact hours</span><input name="hours" disabled={!canManageSettings} value={contact.hours} onChange={(event) => setContact({ ...contact, hours: event.target.value })} /></label><button className="btn md:col-span-3" disabled={!canManageSettings} type="submit">Save contact details</button></form>
  </section>;
}
