"use client";

import { useEffect, useState, type FormEvent } from "react";
import { AdminNotice, AdminPageHeader } from "./presentation";

type User = { id: string; email: string | null; displayName: string; role: "ADMIN" | "MANAGER" | "STAFF" | "CONTENT_CREATOR"; permissions: string[] };
const permissions = ["orders.read", "orders.update", "orders.transition", "orders.payment.write", "customers.read", "customers.write", "catalog.product.write", "catalog.package.write", "availability.write", "availability.sold_out", "delivery.override", "cms.edit", "cms.publish", "media.write", "invoices.issue", "invoices.download", "picking.write", "pickers.manage"];

export function UserModule() {
  const [users, setUsers] = useState<User[]>([]); const [message, setMessage] = useState(""); const [tone, setTone] = useState<"success" | "error">("success"); const [passwordError, setPasswordError] = useState("");
  const feedback = (text: string, nextTone: "success" | "error") => { setMessage(text); setTone(nextTone); };
  async function load() { const response = await fetch("/api/admin/users"); const body = await response.json(); if (response.ok) setUsers(body.data); else feedback(body.code ?? "Permission denied", "error"); }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const response = await fetch("/api/admin/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: values.get("email"), password: values.get("password"), displayName: values.get("displayName"), role: values.get("role") }) }); const body = await response.json(); if (!response.ok) return feedback(body.code ?? body.message ?? "Request failed", "error"); event.currentTarget.reset(); feedback("User created.", "success"); await load(); }
  async function grant(user: User, permission: string, granted: boolean) { const response = await fetch(`/api/admin/users/${user.id}/permissions`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ permission, granted }) }); const body = await response.json(); if (!response.ok) return feedback(body.code ?? body.message ?? "Request failed", "error"); setUsers((rows) => rows.map((row) => row.id === user.id ? { ...row, permissions: granted ? [...new Set([...row.permissions, permission])] : row.permissions.filter((item) => item !== permission) } : row)); }
  async function resetPassword(user: User) { const response = await fetch(`/api/admin/users/${user.id}/password`, { method: "POST" }); const body = await response.json(); if (!response.ok) return feedback(body.message ?? "Password reset failed", "error"); window.alert(`Temporary password for ${user.email}:\n\n${body.data.temporaryPassword}\n\nCopy it now. It cannot be recovered later.`); }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPasswordError(""); const values = new FormData(event.currentTarget); const response = await fetch("/api/auth/change-password", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ currentPassword: values.get("currentPassword"), newPassword: values.get("newPassword") }) }); const body = await response.json(); if (!response.ok) { setPasswordError(body.message ?? "Password change failed"); return; } event.currentTarget.reset(); feedback("Password changed.", "success"); }
  return <section className="shell pb-10"><AdminPageHeader eyebrow="ADMINISTRATION" title="Users & permissions" description="Manage staff access and permissions." />{message && <AdminNotice tone={tone} live>{message}</AdminNotice>}<form className="card mt-3 grid gap-3 md:grid-cols-3" onSubmit={changePassword} noValidate><h3 className="font-bold md:col-span-3">Change my password</h3>{passwordError && <AdminNotice tone="error" live>{passwordError}</AdminNotice>}<label className={`field ${passwordError ? "field-invalid" : ""}`}><span>Current password <b aria-hidden="true">*</b></span><input name="currentPassword" type="password" autoComplete="current-password" required aria-invalid={Boolean(passwordError)} /></label><label className={`field ${passwordError ? "field-invalid" : ""}`}><span>New password <b aria-hidden="true">*</b></span><input name="newPassword" type="password" autoComplete="new-password" minLength={8} required aria-invalid={Boolean(passwordError)} /></label><button className="btn" type="submit">Change password</button></form><form className="card mt-3 grid gap-3 md:grid-cols-5" onSubmit={create} noValidate><label className="field"><span>Email <b aria-hidden="true">*</b></span><input name="email" type="email" required /></label><label className="field"><span>Temporary password <b aria-hidden="true">*</b></span><input name="password" type="password" required /></label><label className="field"><span>Display name <b aria-hidden="true">*</b></span><input name="displayName" required minLength={2} /></label><label className="field"><span>Role <b aria-hidden="true">*</b></span><select name="role" defaultValue="STAFF" required><option value="ADMIN">Admin</option><option value="MANAGER">Manager</option><option value="STAFF">Staff</option><option value="CONTENT_CREATOR">Content Creator</option></select></label><button className="btn" type="submit">Create user</button></form><div className="mt-3 grid gap-3">{users.map((user) => <article className="card" key={user.id}><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-bold">{user.displayName} <span className="pill">{user.role}</span></h3><p className="text-sm">{user.email}</p></div><button className="btn btn-secondary" onClick={() => void resetPassword(user)}>Reset password</button></div>{(user.role === "STAFF" || user.role === "CONTENT_CREATOR") && <div className="mt-2 grid gap-2 md:grid-cols-3">{permissions.map((permission) => <label className="flex items-center gap-2 text-sm" key={permission}><input type="checkbox" checked={user.permissions.includes(permission)} onChange={(event) => void grant(user, permission, event.target.checked)} />{permission}</label>)}</div>}</article>)}</div></section>;
}
