import { randomUUID } from "node:crypto";
import { put } from "@vercel/blob";
import { and, asc, eq, count } from "drizzle-orm";
import { db } from "@/db/client";
import { auditEntries, mediaAttachments, mediaAssets, products } from "@/db/schema";
import { requirePermission } from "@/domain/access";
import { DomainError } from "@/domain/errors";
import { env } from "@/lib/env";
import { failure, success } from "../../response";

export const runtime = "nodejs";
const MAX_BYTES = 2 * 1024 * 1024;
const IMAGE_TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);

export async function GET(request: Request) { try { await requirePermission(db(), request, "media.write"); const productId = new URL(request.url).searchParams.get("productId"); if (!productId) throw new DomainError("VALIDATION_ERROR", "Product is required", 422); const rows = await db().select({ attachment: mediaAttachments, asset: mediaAssets }).from(mediaAttachments).innerJoin(mediaAssets, eq(mediaAssets.id, mediaAttachments.assetId)).where(and(eq(mediaAttachments.shopId, env().SHOP_ID), eq(mediaAttachments.productId, productId))).orderBy(asc(mediaAttachments.sortOrder)); return success(rows.map((row) => ({ ...row.asset, sortOrder: row.attachment.sortOrder, isPrimary: row.attachment.isPrimary }))); } catch (error) { return failure(error); } }

export async function POST(request: Request) { try { const actor = await requirePermission(db(), request, "media.write"); const form = await request.formData(); const productId = String(form.get("productId") ?? ""); const file = form.get("file"); const altFi = String(form.get("altFi") ?? "").trim(); const altEn = String(form.get("altEn") ?? "").trim(); if (!(file instanceof File) || !productId || !altFi || !altEn) throw new DomainError("VALIDATION_ERROR", "Product, image, and Finnish/English alt text are required", 422); if (!IMAGE_TYPES.has(file.type)) throw new DomainError("VALIDATION_ERROR", "Only JPEG, PNG, or WebP images are supported", 422); if (file.size > MAX_BYTES) throw new DomainError("VALIDATION_ERROR", "Images must be 2 MB or smaller", 422); const product = await db().query.products.findFirst({ where: and(eq(products.id, productId), eq(products.shopId, env().SHOP_ID)) }); if (!product) throw new DomainError("NOT_FOUND", "Product not found", 404); const existing = await db().select({ total: count() }).from(mediaAttachments).where(and(eq(mediaAttachments.shopId, env().SHOP_ID), eq(mediaAttachments.productId, productId))); if (Number(existing[0]?.total ?? 0) >= 4) throw new DomainError("MEDIA_LIMIT", "A product can have at most 4 images", 409); const now = new Date().toISOString(); const assetId = randomUUID(); const attachmentId = randomUUID(); const blob = await put(`products/${productId}/${file.name}`, file, { access: "public", addRandomSuffix: true, contentType: file.type }); await db().insert(mediaAssets).values({ id: assetId, shopId: env().SHOP_ID, url: blob.url, pathname: blob.pathname, mimeType: file.type, sizeBytes: file.size, altFi, altEn, captionFi: "", captionEn: "", active: true, createdAt: now }); await db().insert(mediaAttachments).values({ id: attachmentId, shopId: env().SHOP_ID, assetId, productId, pageKey: null, sortOrder: Number(existing[0]?.total ?? 0), isPrimary: Number(existing[0]?.total ?? 0) === 0 }); await db().insert(auditEntries).values({ id: randomUUID(), shopId: env().SHOP_ID, actor: actor.email ?? actor.id, action: "media.uploaded", entityType: "product", entityId: productId, detailsJson: JSON.stringify({ assetId, sizeBytes: file.size }), createdAt: now }); return success({ ...blob, id: assetId, altFi, altEn }); } catch (error) { return failure(error); } }
