import { randomUUID } from "node:crypto";
import { and, eq, sql } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db/client";
import { orders, orderSources } from "@/db/schema";
import { DomainError } from "@/domain/errors";
import { env } from "@/lib/env";
import { failure, success } from "../../response";
import { executeAdmin, parseJson } from "@/app/api/admin/module";

const input = z.object({ key: z.string().trim().min(2).max(40).regex(/^[A-Z0-9_]+$/), labelFi: z.string().trim().min(2).max(80), labelEn: z.string().trim().min(2).max(80), active: z.boolean().default(true), sortOrder: z.number().int().min(0).default(0) });
const defaults = [{ key: "WEBSITE", labelFi: "Verkkosivu", labelEn: "Website" }, { key: "SMS", labelFi: "SMS", labelEn: "SMS" }, { key: "WHATSAPP", labelFi: "WhatsApp", labelEn: "WhatsApp" }, { key: "FACEBOOK", labelFi: "Facebook-viesti", labelEn: "Facebook message" }, { key: "PHONE", labelFi: "Puhelin", labelEn: "Phone" }, { key: "OTHER", labelFi: "Muu", labelEn: "Other" }];
async function ensureDefaults() { const shopId = env().SHOP_ID; const rows = await db().select().from(orderSources).where(eq(orderSources.shopId, shopId)); if (rows.length) return rows; const now = new Date().toISOString(); await db().insert(orderSources).values(defaults.map((item, index) => ({ id: randomUUID(), shopId, ...item, active: true, sortOrder: index, createdAt: now, updatedAt: now }))); return db().select().from(orderSources).where(eq(orderSources.shopId, shopId)); }
export async function GET(request: Request) { try { return success(await executeAdmin(request, { permission: "settings.sources.read", parse: async () => undefined, run: async () => (await ensureDefaults()).sort((a, b) => a.sortOrder - b.sortOrder) })); } catch (error) { return failure(error); } }
export async function POST(request: Request) { try { return success(await executeAdmin(request, { permission: "settings.sources.manage", parse: async (inputRequest) => { const parsed = input.safeParse(await parseJson(inputRequest)); if (!parsed.success) throw new DomainError("VALIDATION_ERROR", "Invalid order source", 422); return parsed.data; }, run: async (parsed, { database, context }) => { const now = new Date().toISOString(); const [row] = await database.insert(orderSources).values({ id: randomUUID(), shopId: env().SHOP_ID, ...parsed, createdAt: now, updatedAt: now }).returning(); if (!row) throw new DomainError("CREATE_FAILED", "Order source could not be created", 500); return { ...row, updatedBy: context.actor.email ?? context.actor.id }; } }), 201); } catch (error) { return failure(error); } }
export async function PATCH(request: Request) { try { return success(await executeAdmin(request, { permission: "settings.sources.manage", parse: async (inputRequest) => { const body = await parseJson(inputRequest) as { id?: string } & Partial<z.infer<typeof input>>; if (!body.id) throw new DomainError("VALIDATION_ERROR", "Source id is required", 422); const parsed = input.partial().safeParse(body); if (!parsed.success) throw new DomainError("VALIDATION_ERROR", "Invalid order source", 422); return { id: body.id, values: parsed.data }; }, run: async ({ id, values }, { database, context }) => { const [row] = await database.update(orderSources).set({ ...values, updatedAt: new Date().toISOString() }).where(and(eq(orderSources.id, id), eq(orderSources.shopId, env().SHOP_ID))).returning(); if (!row) throw new DomainError("NOT_FOUND", "Order source not found", 404); return { ...row, updatedBy: context.actor.email ?? context.actor.id }; } })); } catch (error) { return failure(error); } }
export async function DELETE(request: Request) { try { return success(await executeAdmin(request, { permission: "settings.sources.manage", parse: async (inputRequest) => { const id = new URL(inputRequest.url).searchParams.get("id"); if (!id) throw new DomainError("VALIDATION_ERROR", "Source id is required", 422); return id; }, run: async (id, { database, context }) => { const current = await database.query.orderSources.findFirst({ where: and(eq(orderSources.id, id), eq(orderSources.shopId, env().SHOP_ID)) }); if (!current) throw new DomainError("NOT_FOUND", "Order source not found", 404); if (["WEBSITE", "MANUAL", "HISTORICAL"].includes(current.key)) throw new DomainError("FORBIDDEN", "Cannot delete system core channel. Deactivate it instead.", 409); const [{ count }] = await database.select({ count: sql<number>`count(*)` }).from(orders).where(and(eq(orders.shopId, env().SHOP_ID), eq(orders.orderSource, current.key))); if (Number(count) > 0) throw new DomainError("CONFLICT", `Cannot delete channel: used in ${count} historical orders. Deactivate it instead.`, 409); await database.delete(orderSources).where(and(eq(orderSources.id, id), eq(orderSources.shopId, env().SHOP_ID))); return { deleted: true, id, updatedBy: context.actor.email ?? context.actor.id }; } })); } catch (error) { return failure(error); } }
