#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE="${ENV_FILE:-.env.local}"

banner "Metsänilo local Turso dev setup"

stage "Check local tools"
say "This wizard configures a local Turso dev server, initializes the database, and prepares the admin login."
step "Confirm Node.js and npm are installed."
node --version
npm --version
step "Confirm the Turso CLI is installed and available."
if ! command -v turso >/dev/null 2>&1; then
  warn "Turso CLI is not installed. Install it from https://docs.turso.tech/cli/installation, then re-run this wizard."
  exit 1
fi
turso version

stage "Choose the local Turso database"
say "The app will connect to a Turso local development server backed by a persistent SQLite file."
ask TURSO_DEV_DB_FILE "Database file name [local.db]:"
TURSO_DEV_DB_FILE="${TURSO_DEV_DB_FILE:-local.db}"
ask TURSO_DEV_PORT "Turso dev port [8080]:"
TURSO_DEV_PORT="${TURSO_DEV_PORT:-8080}"
TURSO_DATABASE_URL="http://127.0.0.1:${TURSO_DEV_PORT}"
TURSO_AUTH_TOKEN=""
write_env TURSO_DATABASE_URL "$TURSO_DATABASE_URL"
write_env TURSO_AUTH_TOKEN "$TURSO_AUTH_TOKEN"
write_env TURSO_DEV_DB_FILE "$TURSO_DEV_DB_FILE"
write_env TURSO_DEV_PORT "$TURSO_DEV_PORT"
if [[ -f "$TURSO_DEV_DB_FILE" ]] && ! confirm "The database file already exists. Continue and allow the seed safety gate to decide what can be changed?"; then
  exit 1
fi
say "Starting Turso dev on $TURSO_DATABASE_URL ..."
turso dev --db-file "$TURSO_DEV_DB_FILE" --port "$TURSO_DEV_PORT" > .turso-dev.log 2>&1 &
TURSO_DEV_PID=$!
write_env TURSO_DEV_PID "$TURSO_DEV_PID"
sleep 1
if ! kill -0 "$TURSO_DEV_PID" 2>/dev/null; then
  warn "Turso dev stopped. Check .turso-dev.log for details."
  exit 1
fi

stage "Configure shop identity"
say "These values appear on the storefront and in admin operations."
ask SHOP_ID "Shop ID [shop-main]:"; SHOP_ID="${SHOP_ID:-shop-main}"
ask SHOP_SLUG "Shop slug [metsanilo]:"; SHOP_SLUG="${SHOP_SLUG:-metsanilo}"
ask SHOP_NAME_FI "Shop name in Finnish:"
ask SHOP_NAME_EN "Shop name in English:"
ask SHOP_TIMEZONE "Shop timezone [Europe/Helsinki]:"; SHOP_TIMEZONE="${SHOP_TIMEZONE:-Europe/Helsinki}"
write_env SHOP_ID "$SHOP_ID"; write_env SHOP_SLUG "$SHOP_SLUG"; write_env SHOP_NAME_FI "$SHOP_NAME_FI"; write_env SHOP_NAME_EN "$SHOP_NAME_EN"; write_env SHOP_TIMEZONE "$SHOP_TIMEZONE"

stage "Configure pickup and contact details"
say "Enter the customer-facing pickup instructions and contact details."
ask PICKUP_NAME_FI "Pickup name in Finnish:"
ask PICKUP_NAME_EN "Pickup name in English:"
ask PICKUP_ADDRESS "Pickup address:"
ask PICKUP_INSTRUCTIONS_FI "Pickup instructions in Finnish:"
ask PICKUP_INSTRUCTIONS_EN "Pickup instructions in English:"
ask PICKUP_TIME "Pickup time [20:00]:"; PICKUP_TIME="${PICKUP_TIME:-20:00}"
ask CONTACT_PHONE "Contact phone:"
ask CONTACT_EMAIL "Contact email:"
ask CONTACT_HOURS "Contact hours:"
write_env PICKUP_NAME_FI "$PICKUP_NAME_FI"; write_env PICKUP_NAME_EN "$PICKUP_NAME_EN"; write_env PICKUP_ADDRESS "$PICKUP_ADDRESS"; write_env PICKUP_INSTRUCTIONS_FI "$PICKUP_INSTRUCTIONS_FI"; write_env PICKUP_INSTRUCTIONS_EN "$PICKUP_INSTRUCTIONS_EN"; write_env PICKUP_TIME "$PICKUP_TIME"; write_env CONTACT_PHONE "$CONTACT_PHONE"; write_env CONTACT_EMAIL "$CONTACT_EMAIL"; write_env CONTACT_HOURS "$CONTACT_HOURS"

stage "Create the local admin account"
say "This account is used to sign in at http://localhost:3000/admin."
ask BOOTSTRAP_ADMIN_EMAIL "Admin email [admin@metsanilo.local]:"; BOOTSTRAP_ADMIN_EMAIL="${BOOTSTRAP_ADMIN_EMAIL:-admin@metsanilo.local}"
ask_secret BOOTSTRAP_ADMIN_PASSWORD "Admin password:"
ask ADMIN_DISPLAY_NAME "Admin display name [Shop Admin]:"; ADMIN_DISPLAY_NAME="${ADMIN_DISPLAY_NAME:-Shop Admin}"
write_env BOOTSTRAP_ADMIN_EMAIL "$BOOTSTRAP_ADMIN_EMAIL"; write_env BOOTSTRAP_ADMIN_PASSWORD "$BOOTSTRAP_ADMIN_PASSWORD"; write_env ADMIN_DISPLAY_NAME "$ADMIN_DISPLAY_NAME"

stage "Generate local auth secrets"
say "The wizard generates local-only secrets; nothing is sent to GitHub or a third-party service."
ADMIN_SESSION_SECRET="$(openssl rand -hex 32 2>/dev/null || node -e 'console.log(require("node:crypto").randomBytes(32).toString("hex"))')"
BETTER_AUTH_SECRET="$(openssl rand -hex 32 2>/dev/null || node -e 'console.log(require("node:crypto").randomBytes(32).toString("hex"))')"
write_env ADMIN_SESSION_SECRET "$ADMIN_SESSION_SECRET"
write_env BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"
write_env BETTER_AUTH_ENABLED "true"
write_env BETTER_AUTH_URL "http://localhost:3000/api/auth/better"

stage "Add the first product seed"
say "Seed one product and its package so the storefront has usable local data. Use integer millilitres and cents."
ask SEED_PRODUCT_CODE "Product code [blueberry]:"; SEED_PRODUCT_CODE="${SEED_PRODUCT_CODE:-blueberry}"
ask SEED_PRODUCT_NAME_FI "Product name in Finnish:"
ask SEED_PRODUCT_NAME_EN "Product name in English:"
ask SEED_PACKAGE_LABEL_FI "Package label in Finnish:"
ask SEED_PACKAGE_LABEL_EN "Package label in English:"
ask SEED_PACKAGE_ML "Package volume in millilitres:"
ask SEED_PACKAGE_PRICE_CENTS "Package price in cents:"
ask SEED_AVAILABLE_FROM "Availability start (YYYY-MM-DD):"
ask SEED_AVAILABLE_THROUGH "Availability end (YYYY-MM-DD):"
ask SEED_DAILY_CAPACITY_ML "Daily capacity in millilitres:"
write_env SEED_PRODUCT_CODE "$SEED_PRODUCT_CODE"; write_env SEED_PRODUCT_NAME_FI "$SEED_PRODUCT_NAME_FI"; write_env SEED_PRODUCT_NAME_EN "$SEED_PRODUCT_NAME_EN"; write_env SEED_PACKAGE_LABEL_FI "$SEED_PACKAGE_LABEL_FI"; write_env SEED_PACKAGE_LABEL_EN "$SEED_PACKAGE_LABEL_EN"; write_env SEED_PACKAGE_ML "$SEED_PACKAGE_ML"; write_env SEED_PACKAGE_PRICE_CENTS "$SEED_PACKAGE_PRICE_CENTS"; write_env SEED_AVAILABLE_FROM "$SEED_AVAILABLE_FROM"; write_env SEED_AVAILABLE_THROUGH "$SEED_AVAILABLE_THROUGH"; write_env SEED_DAILY_CAPACITY_ML "$SEED_DAILY_CAPACITY_ML"

stage "Migrate and seed the local database"
say "The repository scripts will validate the configuration, apply migrations, and seed the shop."
export TURSO_DATABASE_URL TURSO_AUTH_TOKEN SHOP_ID SHOP_SLUG SHOP_NAME_FI SHOP_NAME_EN SHOP_TIMEZONE PICKUP_NAME_FI PICKUP_NAME_EN PICKUP_ADDRESS PICKUP_INSTRUCTIONS_FI PICKUP_INSTRUCTIONS_EN PICKUP_TIME CONTACT_PHONE CONTACT_EMAIL CONTACT_HOURS BOOTSTRAP_ADMIN_EMAIL BOOTSTRAP_ADMIN_PASSWORD ADMIN_DISPLAY_NAME ADMIN_SESSION_SECRET BETTER_AUTH_SECRET BETTER_AUTH_ENABLED BETTER_AUTH_URL SEED_PRODUCT_CODE SEED_PRODUCT_NAME_FI SEED_PRODUCT_NAME_EN SEED_PACKAGE_LABEL_FI SEED_PACKAGE_LABEL_EN SEED_PACKAGE_ML SEED_PACKAGE_PRICE_CENTS SEED_AVAILABLE_FROM SEED_AVAILABLE_THROUGH SEED_DAILY_CAPACITY_ML
step "Run environment preflight."
npm run db:preflight
step "Apply migrations."
npm run db:migrate
if [[ -f "$TURSO_DEV_DB_FILE" ]] && grep -q "CREATE TABLE" "$TURSO_DEV_DB_FILE" 2>/dev/null; then
  warn "The database already contains schema. The seed script may refuse an existing shop unless SEED_ALLOW_EXISTING=true."
fi
if confirm "Run the seed now?"; then
  npm run db:seed
else
  SKIPPED+=("Database seed (run npm run db:seed after reviewing .env.local)")
fi

finish
