import Link from "next/link";
import { isLocale, type Locale } from "@/lib/format";
import { LocaleDocument } from "./locale-document";

type InfoKind = "how-it-works" | "reviews" | "about";

const navCopy = {
  fi: { how: "Miten varaus toimii", reviews: "Arvostelut", about: "Meistä", reserve: "Varaa tuotteet", contact: "Yhteys" },
  en: { how: "How it works", reviews: "Reviews", about: "About us", reserve: "Reserve products", contact: "Contact" },
} satisfies Record<Locale, Record<string, string>>;

const content = {
  fi: {
    "how-it-works": { eyebrow: "Näin se toimii", title: "Miten varaus toimii", intro: "Metsänilo yhdistää Satakunnan metsien puhtaan sadon helppoon paikalliseen toimitukseen.", ctaTitle: "Valmis nauttimaan tuoreesta sadosta?", cta: "Tee varaus nyt", steps: [["1", "Valitse marjat ja varaa", "Valitse marja, pakkauskoko ja nouto tai kotiinkuljetus."], ["2", "Henkilökohtainen vahvistus", "Tarkistamme päivän sadon ja vahvistamme varauksesi WhatsAppilla, tekstiviestillä tai puhelimitse."], ["3", "Nouda tai vastaanota toimitus", "Nouda sovittuna aikana tai vastaanota puhdistetut marjat kotiovellesi."]] },
    reviews: { eyebrow: "Asiakasarvostelut", title: "Mitä asiakkaamme sanovat", intro: "Aito palaute auttaa meitä pitämään sadon ja palvelun hyvänä.", formTitle: "Jaa oma kokemuksesi", formText: "Otamme mielellämme palautetta vastaan. Lähetä meille viesti, niin voimme lisätä kokemuksesi seuraavaan arvostelukokoelmaan.", cta: "Varaa marjoja", reviews: [["Liisa K.", "Aivan mahtavan puhdasta ja makeaa mustikkaa! Pakastimeen meni heti 10 litraa.", "Puhdistettu metsämustikka"], ["Tero M.", "Kotiinkuljetus Porin keskustaan toimi täydellisesti ja marjat olivat ensiluokkaisia.", "Villivadelma"]] },
    about: { eyebrow: "Meidän tarinamme", title: "METSÄNILO — Satakunnan luonto & sato", quote: "METSÄNILO syntyi halusta tuoda Satakunnan puhtaiden metsien parhaat herkut suoraan jokaisen kodin pöytään.", body: "Toimimme Porissa ja lähikunnissa. Hankimme marjat vastuullisesti paikallisilta poimijoilta. Jokainen erä puhdistetaan huolellisesti ja tarkistetaan käsin ennen pakkaamista.", values: [["100 % puhdistettu sato", "Marjat imurointipuhdistetaan ja tarkistetaan käsin lehtien ja roskien poistamiseksi."], ["Paikallista ja reilua", "Tuemme paikallisia marjanpoimijoita reilulla päiväkorvauksella ja tuomme tuoreen sadon kaikkien ulottuville."]], cta: "Tutustu tuotteisiin" },
  },
  en: {
    "how-it-works": { eyebrow: "Simple steps", title: "How ordering works", intro: "METSÄNILO connects fresh forest berries with smooth local delivery in Satakunta.", ctaTitle: "Ready to enjoy fresh wild berries?", cta: "Make a reservation", steps: [["1", "Select berries & reserve", "Choose your berries, package size and pickup or local delivery."], ["2", "Personal confirmation", "We check the daily harvest and confirm your reservation via WhatsApp, SMS or phone."], ["3", "Pickup or local delivery", "Pick up at the agreed time or receive freshly cleaned berries at your door."]] },
    reviews: { eyebrow: "Customer reviews", title: "What our customers say", intro: "Real feedback helps us keep both the harvest and service at their best.", formTitle: "Share your experience", formText: "We would love to hear from you. Send us a message and we can include your experience in our next review collection.", cta: "Reserve berries", reviews: [["Liisa K.", "Incredibly clean and sweet blueberries. Ten litres went straight into the freezer.", "Cleaned wild blueberries"], ["Tero M.", "Home delivery in central Pori worked perfectly and the berries were excellent.", "Wild raspberries"]] },
    about: { eyebrow: "Our story", title: "METSÄNILO — Satakunnan nature & harvest", quote: "METSÄNILO was born from a desire to bring the finest delicacies of Satakunta's pure wild forests directly to every household table.", body: "We operate in Pori and surrounding municipalities. We source berries responsibly from local pickers. Every batch is carefully cleaned and hand-checked before bucket packaging.", values: [["100% cleaned harvest", "Berries are vacuum cleaned and hand inspected to remove leaves and debris."], ["Local & fair sourcing", "We support local berry pickers with fair daily compensation and bring fresh harvest to everyone."]], cta: "Explore the harvest" },
  },
} as const;

export function InfoPage({ locale, kind, contactEmail }: { locale: Locale; kind: InfoKind; contactEmail?: string | null }) {
  // The three page variants intentionally have different content shapes; the
  // branch below narrows the shape at render time.
  const t = content[locale][kind] as any;
  const nav = navCopy[locale];
  const other = locale === "fi" ? "en" : "fi";
  return <main className="storefront info-page"><LocaleDocument locale={locale} /><header className="storefront-header"><div className="shell storefront-nav"><Link className="brand-lockup" href={`/${locale}`}><span className="brand-mark" aria-hidden="true"><i /><i /><i /></span><span><strong>METSÄNILO</strong></span></Link><nav className="storefront-nav-links" aria-label={locale === "fi" ? "Päävalikko" : "Main navigation"}><Link className="nav-reserve-link" href={`/${locale}/reserve`}>{nav.reserve}</Link><Link href={`/${locale}/how-it-works`}>{nav.how}</Link><Link href={`/${locale}/reviews`}>{nav.reviews}</Link><Link href={`/${locale}/about`}>{nav.about}</Link></nav><Link className="locale-switch" href={`/${other}/${kind}`} hrefLang={other}>{locale === "fi" ? "English" : "Suomeksi"}<span aria-hidden="true">↗</span></Link></div></header>
    {kind === "how-it-works" && <><section className="shell info-hero" aria-labelledby="info-title"><p className="eyebrow">{t.eyebrow}</p><h1 id="info-title">{t.title}</h1><p>{t.intro}</p></section><section className="shell info-grid" aria-label={t.title}>{t.steps.map(([number, title, text]: [string, string, string]) => <article className="info-step-card" key={number}><span className="info-number">{number}</span><h2>{title}</h2><p>{text}</p></article>)}</section><InfoCta locale={locale} title={t.ctaTitle} label={t.cta} /></>}
    {kind === "reviews" && <><section className="shell info-hero" aria-labelledby="info-title"><p className="eyebrow">{t.eyebrow}</p><h1 id="info-title">{t.title}</h1><p>{t.intro}</p></section><section className="shell review-grid" aria-label={t.title}>{t.reviews.map(([name, quote, product]: [string, string, string]) => <article className="review-card" key={name}><div className="review-card-head"><h2>{name}</h2><span className="review-stars" aria-label="5 stars">★★★★★</span></div><p className="review-quote">“{quote}”</p><span className="review-product">{product}</span></article>)}</section><section className="shell review-invite"><p className="eyebrow">{locale === "fi" ? "Palaute" : "Your voice"}</p><h2>{t.formTitle}</h2><p>{t.formText}</p>{contactEmail ? <a className="btn btn-accent" href={`mailto:${contactEmail}`}>{locale === "fi" ? "Lähetä palautetta" : "Send feedback"}<span aria-hidden="true">→</span></a> : <Link className="btn btn-accent" href={`/${locale}/reserve`}>{t.cta}<span aria-hidden="true">→</span></Link>}</section></>}
    {kind === "about" && <><section className="shell info-hero" aria-labelledby="info-title"><p className="eyebrow">{t.eyebrow}</p><h1 id="info-title">{t.title}</h1></section><section className="shell story-card"><p className="story-quote">“{t.quote}”</p><p className="story-body">{t.body}</p><div className="value-grid">{t.values.map(([title, text]: [string, string], index: number) => <article className={index === 0 ? "value-card value-card-green" : "value-card value-card-gold"} key={title}><h2>{title}</h2><p>{text}</p></article>)}</div></section><InfoCta locale={locale} title={locale === "fi" ? "Löydä seuraava suosikkisi" : "Find your next favourite"} label={t.cta} /></>}
    <footer className="storefront-footer"><div className="shell footer-grid"><div><strong>METSÄNILO</strong><p>{locale === "fi" ? "Satakunnan metsästä pöytään · Kausi 2026" : "From Satakunta forest to table · Season 2026"}</p></div><div><span>{nav.contact}</span>{contactEmail && <a href={`mailto:${contactEmail}`}>{contactEmail}</a>}<Link href={`/${locale}/reserve`}>{nav.reserve}</Link></div><div><span>{locale === "fi" ? "Tietoa" : "Information"}</span><Link href={locale === "fi" ? "/fi/tietosuoja" : "/en/privacy"}>{locale === "fi" ? "Tietosuojaseloste" : "Privacy notice"}</Link></div></div></footer><Link className="mobile-reserve-cta" href={`/${locale}/reserve`}>{nav.reserve}<span aria-hidden="true">→</span></Link>
  </main>;
}

function InfoCta({ locale, title, label }: { locale: Locale; title: string; label: string }) { return <section className="shell info-cta"><h2>{title}</h2><p>{locale === "fi" ? "Varaa marjat ennen kuin päivän satokapasiteetti täyttyy." : "Reserve your berries before daily harvest capacity is full."}</p><Link className="btn btn-accent" href={`/${locale}/reserve`}>{label}<span aria-hidden="true">→</span></Link></section>; }

export function isInfoLocale(value: string): value is Locale { return isLocale(value); }
