"use client";

import { useState, type FormEvent } from "react";
import { AdminNotice, AdminStatusBadge } from "../../presentation";

type Customer = { id: string; name: string; mobile: string | null; email: string | null; facebookProfile?: string | null; matchStatus: string; notes: string | null; updatedAt: string; marketingConsent: boolean; marketingConsentStatus: "NOT_CONSENTED" | "CONSENTED" | "REVOKED"; marketingConsentAt: string | null; marketingConsentSource: string | null; marketingConsentUpdatedBy: string | null };
type Order = { id: string; publicReference: string; status: string; fulfillmentDate: string; fulfillmentMethod: string; volumeMl: number; finalTotalCents: number | null; createdAt: string };
type Profile = { customer: Customer; orders: Order[]; audit: Array<{ id: string; action: string; actor: string; createdAt: string }>; metrics: { lifetimeLitres: number; totalSpendCents: number; totalOrders: number; lastFulfillmentDate: string | null }; identityConflicts: Array<{ id: string; name: string; mobile: string | null; email: string | null }> };

const money = (cents: number | null) => cents === null ? "—" : new Intl.NumberFormat("fi-FI", { style: "currency", currency: "EUR" }).format(cents / 100);
const date = (value: string) => new Intl.DateTimeFormat("fi-FI", { dateStyle: "medium" }).format(new Date(value));

export function CustomerProfileView({ initial, canResolveIdentity, canEdit = true, canConsent = true, canAnonymize = false }: { initial: Profile; canResolveIdentity: boolean; canEdit?: boolean; canConsent?: boolean; canAnonymize?: boolean }) {
  const [profile, setProfile] = useState(initial);
  const [message, setMessage] = useState("");
  const [editing, setEditing] = useState(false);
  const [confirmingAnonymize, setConfirmingAnonymize] = useState(false);
  const [identityAction, setIdentityAction] = useState<"MERGE" | "KEEP_SEPARATE" | null>(null);

  async function edit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const values = new FormData(event.currentTarget);
    const response = await fetch(`/api/admin/customers/${profile.customer.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: values.get("name"), mobile: values.get("mobile"), email: values.get("email") }) });
    const body = await response.json(); if (!response.ok) return setMessage(body.message ?? "Customer update failed");
    setProfile((current) => ({ ...current, customer: { ...current.customer, ...body.data } })); setEditing(false); setMessage("Customer updated.");
  }

  async function updateMarketingConsent(marketingConsent: boolean) {
    const response = await fetch(`/api/admin/customers/${profile.customer.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: profile.customer.name, mobile: profile.customer.mobile, email: profile.customer.email ?? "", marketingConsent }) });
    const body = await response.json(); if (!response.ok) return setMessage(body.message ?? "Consent update failed"); setProfile((current) => ({ ...current, customer: body.data })); setMessage(marketingConsent ? "Marketing consent granted." : "Marketing consent revoked.");
  }

  async function resolveIdentity(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!identityAction) return; const values = new FormData(event.currentTarget);
    const response = await fetch(`/api/admin/customers/${profile.customer.id}/identity`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: identityAction, duplicateId: values.get("duplicateId"), reason: values.get("reason") }) });
    const body = await response.json(); if (!response.ok) return setMessage(body.message ?? "Identity resolution failed");
    setIdentityAction(null); setProfile((current) => ({ ...current, customer: { ...current.customer, matchStatus: "ACTIVE" }, identityConflicts: [{ id: current.customer.id, name: current.customer.name, mobile: current.customer.mobile, email: current.customer.email }] })); setMessage(identityAction === "MERGE" ? "Customer records merged." : "Identity marked as reviewed and kept separate.");
  }

  async function anonymize() {
    const response = await fetch(`/api/admin/customers/${profile.customer.id}`, { method: "POST" }); const body = await response.json(); if (!response.ok) return setMessage(body.message ?? "Anonymization failed");
    setProfile((current) => ({ ...current, customer: { ...current.customer, name: "Anonymized customer", mobile: "ANONYMIZED", email: null, marketingConsent: false, marketingConsentStatus: "REVOKED" } })); setConfirmingAnonymize(false); setMessage("Customer anonymized.");
  }

  return <div className="customer-profile-layout">
    {message && <AdminNotice tone="success" live>{message}</AdminNotice>}
    {profile.identityConflicts.length > 1 && <section className="customer-identity-warning" role="alert"><strong>⚠ Identity review needed</strong><span>{profile.identityConflicts.length} customer records share this mobile number.</span>{canResolveIdentity ? <div className="profile-actions"><button className="btn btn-secondary" type="button" onClick={() => setIdentityAction("MERGE")}>Merge</button><button className="btn btn-secondary" type="button" onClick={() => setIdentityAction("KEEP_SEPARATE")}>Keep separate</button></div> : <small>Ask a user with identity-resolution permission.</small>}</section>}
    <section className="customer-metrics-grid" aria-label="Customer lifetime summary"><div className="card"><span>Lifetime litres</span><strong>{(profile.metrics.lifetimeLitres / 1000).toLocaleString("fi-FI", { maximumFractionDigits: 1 })} L</strong></div><div className="card"><span>Total spend</span><strong>{money(profile.metrics.totalSpendCents)}</strong></div><div className="card"><span>Total orders</span><strong>{profile.metrics.totalOrders}</strong></div><div className="card"><span>Last fulfillment</span><strong>{profile.metrics.lastFulfillmentDate ? date(profile.metrics.lastFulfillmentDate) : "—"}</strong></div></section>
    <section className="card customer-profile-card"><div className="profile-card-heading"><div className="profile-avatar-large">{profile.customer.name.slice(0, 1).toUpperCase()}</div><div><p className="eyebrow">Contact details</p><h2>{profile.customer.name}</h2><p>{profile.customer.mobile}{profile.customer.email ? ` · ${profile.customer.email}` : ""}</p></div><AdminStatusBadge status={profile.customer.matchStatus} label={profile.customer.matchStatus.replaceAll("_", " ")} /></div>{profile.customer.notes && <p className="profile-muted">{profile.customer.notes}</p>}<div className="profile-actions">{canEdit && <button className="btn" type="button" onClick={() => setEditing(true)}>Edit details</button>}{canAnonymize && <button className="btn btn-secondary" type="button" onClick={() => setConfirmingAnonymize(true)}>Anonymize</button>}</div></section>
    <section className="card customer-profile-card"><div className="section-inline-heading"><div><p className="eyebrow">Communication preference</p><h2>Marketing messages</h2></div><AdminStatusBadge status={profile.customer.marketingConsentStatus === "CONSENTED" ? "PAID" : profile.customer.marketingConsentStatus === "REVOKED" ? "CANCELLED" : "UNPAID"} label={profile.customer.marketingConsentStatus === "CONSENTED" ? "Consented" : profile.customer.marketingConsentStatus === "REVOKED" ? "Revoked" : "Do not send marketing"} /></div><p className="profile-muted">SMS and WhatsApp seasonal offers. Operational reservation messages are handled separately.</p>{profile.customer.marketingConsentAt && <p className="text-sm">{profile.customer.marketingConsentStatus === "CONSENTED" ? "Granted" : "Revoked"} {date(profile.customer.marketingConsentAt)} · Source: {profile.customer.marketingConsentSource === "ORDER_FORM" ? "Web form" : profile.customer.marketingConsentSource === "ADMIN" ? "Admin" : profile.customer.marketingConsentSource ?? "Manual"}{profile.customer.marketingConsentUpdatedBy ? ` · ${profile.customer.marketingConsentUpdatedBy}` : ""}</p>}{canConsent && <div className="profile-actions"><button className="btn btn-secondary" type="button" onClick={() => void updateMarketingConsent(!profile.customer.marketingConsent)}>{profile.customer.marketingConsent ? "Revoke consent" : "Grant consent"}</button></div>}</section>
    <section className="card customer-profile-card"><div className="section-inline-heading"><div><p className="eyebrow">History</p><h2>Orders</h2></div><span className="pill">{profile.orders.length} records</span></div><div className="customer-history-list">{profile.orders.length === 0 && <p className="profile-muted">No orders recorded.</p>}{profile.orders.map((order) => <a className="customer-history-row" href={`/admin/orders/${order.id}`} key={order.id}><div><strong>{order.publicReference}</strong><p>{date(order.createdAt)} · {order.fulfillmentMethod} · {order.volumeMl / 1000} L</p></div><div><AdminStatusBadge status={order.status} /><p>{money(order.finalTotalCents)}</p></div></a>)}</div></section>
    <section className="card customer-profile-card"><div className="section-inline-heading"><div><p className="eyebrow">Privacy &amp; activity</p><h2>Audit trail</h2></div></div><div className="customer-audit-list">{profile.audit.length === 0 && <p className="profile-muted">No customer changes recorded.</p>}{profile.audit.map((event) => <div className="customer-audit-row" key={event.id}><strong>{event.action.replace("customer.", "")}</strong><span>{event.actor} · {date(event.createdAt)}</span></div>)}</div></section>
    {editing && <div className="admin-dialog-backdrop"><form className="admin-dialog card" onSubmit={(event) => void edit(event)}><p className="eyebrow">Edit customer</p><h2>Contact details</h2><label className="field"><span>Name *</span><input name="name" defaultValue={profile.customer.name} required minLength={2} /></label><label className="field"><span>Mobile</span><input name="mobile" defaultValue={profile.customer.mobile ?? ""} minLength={7} /></label><label className="field"><span>Email</span><input name="email" type="email" defaultValue={profile.customer.email ?? ""} /></label><div className="profile-actions"><button className="btn btn-secondary" type="button" onClick={() => setEditing(false)}>Cancel</button><button className="btn" type="submit">Save details</button></div></form></div>}
    {identityAction && <div className="admin-dialog-backdrop"><form className="admin-dialog card" onSubmit={(event) => void resolveIdentity(event)}><p className="eyebrow">IDENTITY REVIEW</p><h2>{identityAction === "MERGE" ? "Merge customer records?" : "Keep records separate?"}</h2>{identityAction === "MERGE" && <label className="field"><span>Record to merge *</span><select name="duplicateId" required>{profile.identityConflicts.filter((item) => item.id !== profile.customer.id).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.email ?? item.mobile}</option>)}</select></label>}<label className="field"><span>Resolution reason *</span><textarea name="reason" minLength={2} required placeholder="Confirm how the customer identity was resolved" /></label><div className="profile-actions"><button className="btn btn-secondary" type="button" onClick={() => setIdentityAction(null)}>Cancel</button><button className="btn" type="submit">Save resolution</button></div></form></div>}
    {confirmingAnonymize && <div className="admin-dialog-backdrop"><section className="admin-dialog card"><p className="eyebrow">Privacy action</p><h2>Anonymize customer?</h2><p className="profile-muted">This removes personal contact details and cannot be undone.</p><div className="profile-actions"><button className="btn btn-secondary" type="button" onClick={() => setConfirmingAnonymize(false)}>Keep details</button><button className="btn btn-danger" type="button" onClick={() => void anonymize()}>Anonymize</button></div></section></div>}
  </div>;
}
