"use client";
import { useState, type FormEvent } from "react";
import { AdminNotice, AdminPageHeader } from "../presentation";

type Review = { id: string; displayName: string; rating: number; originalText: string; displayText: string | null; source: string; status: string; publicationAcknowledgement: boolean; featured: boolean; createdAt: string; moderationReason: string | null };
export function ReviewsManager({ initial, canCreate, canModerate, canFeature }: { initial: Review[]; canCreate: boolean; canModerate: boolean; canFeature: boolean }) {
  const [rows, setRows] = useState(initial); const [message, setMessage] = useState("");
  async function update(review: Review, patch: Partial<Review> & { status?: string }) { const response = await fetch("/api/admin/reviews", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: review.id, status: patch.status ?? review.status, displayText: patch.displayText ?? review.displayText ?? undefined, featured: patch.featured ?? review.featured }) }); const body = await response.json(); if (!response.ok) return setMessage(body.message ?? body.code ?? "Review update failed"); setRows((current) => current.map((item) => item.id === review.id ? body.data : item)); setMessage("Review updated."); }
  async function confirm(review: Review) { const source = window.prompt("Confirmation source: SMS, WHATSAPP, PHONE or OTHER", "WHATSAPP")?.toUpperCase(); if (!source || !["SMS", "WHATSAPP", "PHONE", "OTHER"].includes(source)) return; const response = await fetch("/api/admin/reviews", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: review.id, status: review.status, confirmSource: source }) }); const body = await response.json(); if (!response.ok) return setMessage(body.message ?? body.code ?? "Confirmation failed"); setRows((current) => current.map((item) => item.id === review.id ? body.data : item)); setMessage("Publication confirmation recorded."); }
  async function createManual(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const response = await fetch("/api/admin/reviews", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ displayName: values.get("displayName"), rating: Number(values.get("rating")), originalText: values.get("originalText"), orderId: values.get("orderId") || undefined }) }); const body = await response.json(); if (!response.ok) return setMessage(body.message ?? body.code ?? "Manual review could not be added"); setRows((current) => [body.data, ...current]); event.currentTarget.reset(); setMessage("Manual review added and waiting for customer confirmation."); }
  return <main className="shell py-8"><AdminPageHeader eyebrow="CONTENT & TRUST" title="Reviews" description="Moderate customer feedback, preserve original text and choose homepage highlights." />{message && <AdminNotice tone="success" live>{message}</AdminNotice>}{canCreate && <form className="card mt-6 grid gap-3 md:grid-cols-4" onSubmit={(event) => void createManual(event)}><h2 className="font-bold md:col-span-4">Add manual review</h2><label className="field"><span>Display name</span><input name="displayName" required minLength={2} /></label><label className="field"><span>Rating</span><select name="rating" defaultValue="5"><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select></label><label className="field"><span>Order ID (optional)</span><input name="orderId" /></label><label className="field md:col-span-4"><span>Original review</span><textarea name="originalText" minLength={10} maxLength={2000} required rows={3} /></label><button className="btn md:col-span-4" type="submit">Add for confirmation</button></form>}<div className="mt-6 grid gap-3">{rows.length === 0 && <p className="card">No reviews yet.</p>}{rows.map((review) => <article className="card grid gap-3" key={review.id}><div className="flex flex-wrap items-center justify-between gap-2"><div><h2>{review.displayName} <span className="pill">{review.status}</span></h2><p className="text-sm">{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)} · {review.source} · {new Date(review.createdAt).toLocaleDateString("fi-FI")}</p></div>{review.featured && <span className="pill">Homepage featured</span>}</div><div><p className="text-sm font-semibold">Original</p><p>{review.originalText}</p>{review.displayText && <><p className="mt-2 text-sm font-semibold">Display text</p><p>{review.displayText}</p></>}</div><p className="text-sm text-slate-600">Publication acknowledgement: {review.publicationAcknowledgement ? "Confirmed" : "Missing"}</p>{canModerate && <div className="profile-actions">{!review.publicationAcknowledgement && review.source === "MANUAL_IMPORT" && <button className="btn btn-secondary" type="button" onClick={() => void confirm(review)}>Record customer confirmation</button>}<button className="btn" type="button" onClick={() => void update(review, { status: "APPROVED" })}>Approve &amp; publish</button><button className="btn btn-secondary" type="button" onClick={() => void update(review, { status: "HIDDEN" })}>Hide</button><button className="btn btn-danger" type="button" onClick={() => void update(review, { status: "REJECTED" })}>Reject</button>{canFeature && review.status === "APPROVED" && <button className="btn btn-secondary" type="button" onClick={() => void update(review, { featured: !review.featured })}>{review.featured ? "Remove homepage feature" : "Feature on homepage"}</button>}</div>}</article>)}</div></main>;
}
